data_ref = [
	{ game: 'Arcadia Quest', set: 'Arcadia Quest', subset: 'Core Box', mini_name: 'Nibbles' },
	{ game: 'Arcadia Quest', set: 'Beyond the Grave', subset: 'Core Box', mini_name: 'Chaz' },
	{ game: 'Arcadia Quest', set: 'Inferno', subset: 'Core Box', mini_name: 'Diana' },
	{ game: 'Imperial Assault', set: 'Imperial Assault', subset: 'Core Box', mini_name: 'Diala Passil' },
	{ game: 'Imperial Assault', set: 'Twin Shadows', subset: 'Core Box', mini_name: 'Biv Bodhrik' },
	{ game: 'Zombicide', set: 'Season 1', subset: 'Core Box', mini_name: 'Amy' },
	{ game: 'Zombicide', set: 'Season 1', subset: 'Core Box', mini_name: 'Doug' },
	{ game: 'Zombicide', set: 'Season 1', subset: 'Core Box', mini_name: 'Josh' },
	{ game: 'Zombicide', set: 'Season 1', subset: 'Core Box', mini_name: 'Ned' },
	{ game: 'Zombicide', set: 'Season 1', subset: 'Core Box', mini_name: 'Phil' },
	{ game: 'Zombicide', set: 'Season 1', subset: 'Core Box', mini_name: 'Wanda' },
	{ game: 'Zombicide', set: 'Season 2', subset: 'Prison Outbreak', mini_name: 'Belle' },
	{ game: 'Zombicide', set: 'Season 2', subset: 'Prison Outbreak', mini_name: 'Grindlock' },
	{ game: 'Zombicide', set: 'Season 2', subset: 'Prison Outbreak', mini_name: 'Joshua' },
	{ game: 'Zombicide', set: 'Season 2', subset: 'Prison Outbreak', mini_name: 'Kim' },
	{ game: 'Zombicide', set: 'Season 2', subset: 'Prison Outbreak', mini_name: 'Shannon' },
	{ game: 'Zombicide', set: 'Season 2', subset: 'Prison Outbreak', mini_name: 'Watts' },
	{ game: 'Zombicide', set: 'Season 2', subset: 'Toxic City Mall', mini_name: 'Derek' },
	{ game: 'Zombicide', set: 'Season 2', subset: 'Toxic City Mall', mini_name: 'Elsa' },
	{ game: 'Zombicide', set: 'Season 2', subset: 'Toxic City Mall', mini_name: 'Neema' },
	{ game: 'Zombicide', set: 'Season 2', subset: 'Toxic City Mall', mini_name: 'Raoul' },
	{ game: 'Zombicide', set: 'Season 3', subset: 'Angry Neighbors', mini_name: 'Adam' },
	{ game: 'Zombicide', set: 'Season 3', subset: 'Angry Neighbors', mini_name: 'Jeff' },
	{ game: 'Zombicide', set: 'Season 3', subset: 'Angry Neighbors', mini_name: 'Julien' },
	{ game: 'Zombicide', set: 'Season 3', subset: 'Angry Neighbors', mini_name: 'Tiff' },
	{ game: 'Zombicide', set: 'Season 3', subset: 'Rue Morgue', mini_name: 'Bear' },
	{ game: 'Zombicide', set: 'Season 3', subset: 'Rue Morgue', mini_name: 'Cathy' },
	{ game: 'Zombicide', set: 'Season 3', subset: 'Rue Morgue', mini_name: 'Dan' },
	{ game: 'Zombicide', set: 'Season 3', subset: 'Rue Morgue', mini_name: 'James' },
	{ game: 'Zombicide', set: 'Season 3', subset: 'Rue Morgue', mini_name: 'Jane' },
	{ game: 'Zombicide', set: 'Season 3', subset: 'Rue Morgue', mini_name: 'Joe' },
	{ game: 'Zombicide', set: 'Season 3', subset: 'Rue Morgue', mini_name: 'Laurie' },
	{ game: 'Zombicide', set: 'Season 3', subset: 'Rue Morgue', mini_name: 'Louise' },
	{ game: 'Zombicide', set: 'Season 3', subset: 'Rue Morgue', mini_name: 'Maddie' },
	{ game: 'Zombicide', set: 'Season 3', subset: 'Rue Morgue', mini_name: 'Parker' },
	{ game: 'Zombicide', set: 'Season 3', subset: 'Rue Morgue', mini_name: 'Terry' },
	{ game: 'Zombicide', set: 'Season 3', subset: 'Rue Morgue', mini_name: 'Travis' },
	{ game: 'Zombicide', set: 'Black Plague', subset: 'Black Plague', mini_name: 'Ann' },
	{ game: 'Zombicide', set: 'Black Plague', subset: 'Black Plague', mini_name: 'Baldric' },
	{ game: 'Zombicide', set: 'Black Plague', subset: 'Black Plague', mini_name: 'Clovis' },
	{ game: 'Zombicide', set: 'Black Plague', subset: 'Black Plague', mini_name: 'Nelly' },
	{ game: 'Zombicide', set: 'Black Plague', subset: 'Black Plague', mini_name: 'Samson' },
	{ game: 'Zombicide', set: 'Black Plague', subset: 'Black Plague', mini_name: 'Silas' },
	{ game: 'Zombicide', set: 'Black Plague', subset: 'Hero Box', mini_name: 'Arnaud' },
	{ game: 'Zombicide', set: 'Black Plague', subset: 'Hero Box', mini_name: 'Glynda' },
	{ game: 'Zombicide', set: 'Black Plague', subset: 'Hero Box', mini_name: 'Julian' },
	{ game: 'Zombicide', set: 'Black Plague', subset: 'Hero Box', mini_name: 'Sylvia' },
	{ game: 'Zombicide', set: 'Black Plague', subset: 'Hero Box', mini_name: 'Tucker' },
	{ game: 'Zombicide', set: 'Black Plague', subset: 'Wulfsburg', mini_name: 'Ariane' },
	{ game: 'Zombicide', set: 'Black Plague', subset: 'Wulfsburg', mini_name: 'Karl' },
	{ game: 'Zombicide', set: 'Black Plague', subset: 'Wulfsburg', mini_name: 'Morrigan' },
	{ game: 'Zombicide', set: 'Black Plague', subset: 'Wulfsburg', mini_name: 'Theo' }
];
